steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cowinbot-321814/github.com/chaithanyamarripati/cowinBot:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cowinbot-321814/github.com/chaithanyamarripati/cowinBot:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy','gcloudsample','--region=asia-south1','--platform=managed','--image=gcr.io/cowinbot-321814/github.com/chaithanyamarripati/cowinBot:$SHORT_SHA']